// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Sounds
	{
		public AudioClip loseSound;
		public AudioClip winSound;

		public AudioClip launchBubbleSound;

		public AudioClip bubbleHitSound;
		public AudioClip bubbleMergeSound;
		public AudioClip bubblePopSound;

		public AudioClip requirementMetSound;

		public AudioClip iceCrackSound;
		public AudioClip crateCrackSound;

		public AudioClip cageEatSound;
		public AudioClip cageHitSound;
		public AudioClip cageVomitSound;

		public AudioClip freezingSound;

		public AudioClip bombExplosionSound;
		public AudioClip bombWickSound;

		public AudioClip bouncePlatformSound;
		public AudioClip powerupSound;

		public AudioClip buttonSound;
	}
}